### ISSUE TITLE
Code implementation issues of GIUNetSpect model

### ISSUE THREAD

**Issue by AliothF** [aramiracle/GIUNet#1]
Hello, I noticed that there are some small problems in the implementation of the GIUNetSpect model in your code models.py file. Maybe it is a typo. SpectPool should be used instead of CentPool.

**Comment by aramiracle** [comment]
Hello, appreciate your review of the project. Your observation is accurate and that was typo. I have corrected it and also it needs to modifying the Laplacian function in methods.py. I believe you should now be able to run main.py successfully.
