### ISSUE TITLE
the three rapid performing models

### ISSUE THREAD

**Issue by zkzqbycg** [aramiracle/GIUNet#3]
Hello author，I have some questions about these three rapid performing models:GINModel,SimpleGraphUNet,GraphUNetTopK.Are there original papers on these three models?

**Comment by aramiracle** [comment]
Hi zkzqbycg!

1. GINModel is AE(Autoencoder) structure with "Graph Isomorphism Network" architecture for graph convolution part of model.
2. SimpleGraphUNet is UNet structure with "Graph Isomorphism Network" architecture for graph convolution part of model.
3. GraphUNetTopK is UNet structure with "Graph Isomorphism Network" architecture for graph convolution part of model with TopK node pooling.

- [TopK pooling with UNet paper](https://arxiv.org/pdf/1905.05178)
- [GIN paper](https://arxiv.org/pdf/1810.00826)

I hope these information helps you.

**Comment by zkzqbycg** [comment]
Thank you very much！
